# docker-compose.yml
services:
  consumer:
    build:
      context: ../
      dockerfile: demo/consumer.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - C2CPO_MASTER_SECRET=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

  producer:
    build:
      context: ../
      dockerfile: demo/producer.Dockerfile
    depends_on:
      - consumer
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_URL=http://consumer:8080
      - C2CPO_MASTER_SECRET=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
